import 'package:bangladesh/Homepage.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class bangladesh_poriciti extends StatelessWidget {
  const bangladesh_poriciti({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Color(0xFFA3E4D7),
      appBar: AppBar(
        backgroundColor: Color(0xFFA3E4D7),
        foregroundColor: Colors.black,
        elevation: 5,
        title: Text("বাংলাদেশের পরিচিতি",
          style: TextStyle(fontSize: 21,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(bottomRight: Radius.circular(30),bottomLeft: Radius.circular(30))
        ),
        actions: <Widget>[
          IconButton(onPressed: (){
            Navigator.push(context, MaterialPageRoute(builder: (context)=>homepage()));
          }, icon: Icon(Icons.water_damage_outlined,size: 25,)),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView(
          children: [
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১-> বাংলাদেশের সাংবিধানিক নাম কি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  'গণপ্রজাতন্ত্রী বাংলাদেশ' (The People's Republic of Bangladesh) ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                    fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(5))
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২-> বাংলাদেশের রাজধানীর নাম কি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ঢাকা ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                    fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩-> বাংলাদেশের বৃহত্তর জেলা কতটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১৯ টি ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪-> বাংলাদেশের কুয়েত সিটি বলা হয় কোন অঞ্চল কে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  খুলনা ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫-> কুতুবদিয়া বাতিঘর নির্মাণ করা হয় কখন?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১৮৪৬ সালে ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৬-> বাংলাদেশের সাথে কয়টি দেশের আন্তর্জাতিক সীমান্ত রয়েছে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২ টি ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৭-> বাংলাদেশের মোট সীমান্ত দৈর্ঘ্য কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৪৭১৯ কি. মি. ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৮-> কর্ণফুলী নদীর তলদেশে দেশের একমাত্র টানেল নির্মাণ করবে কোন দেশ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  চীন ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৯-> ভারতীয় কোন রাজ্যের সাথে বাংলাদেশের কোনো সীমান্ত নাই ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  নাগাল্যান্ড ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১০-> বাংলাদেশের কোন জেলা দুই দেশের সীমানা দ্বারা বেষ্টিত ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  রাঙ্গামাটি ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১১-> বাংলাদেশের সবচেয়ে উঁচু সড়কপথ কোনটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  আলিকদম - থানচি ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১২-> ভারতে অবস্থিত বাংলাদেশের পঞ্চম মিশন কোথায় হচ্ছে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  আসাম ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৩-> ১ জুলাই ২০১৫ কোন আর্থিক প্রতিষ্ঠানটির লাইসেন্স প্রদান করা হয়?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  মেরিডিয়ান ফাইন্যান্স অ্যান্ড ইনভেস্টমেন্ট লি. ।",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৪-> দেশের প্রথম কৃত্রিম উপগ্রহ বঙ্গবন্ধু-১ কোন মহাকাশাযানে উৎক্ষেপণ করা হয়?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ফ্যালকন-৯",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৫-> শেওলা স্থলবন্দর ঘোষণা করা হয় কবে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৩০ জুন ২০১৫",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৬-> দেশের প্রথম নারী তথ্য কর্মকর্তা কে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  কামরুন নাহার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৭-> বাংলাদেশের সমুদ্র উপকূলের দৈর্ঘ্য কত ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৪৪৫ মাইল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৮-> বাংলাদেশের উত্তর অক্ষাংশের অবস্থান কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২০°৩৮'- ২৬°৩৮'",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ১৯-> বাংলাদেশের সীমান্তবর্তী ভারতের রাজ্য কয়টি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৫ টি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২০-> বাংলাদেশের সাথে নিম্নলিখিত কোন দেশের Maritime boundary বিদ্যমান রয়েছে ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  মিয়ানমার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২১-> মিয়ানমার বাংলাদেশের কোনদিকে অবস্থিত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  দক্ষিণপূর্ব",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২২-> ভারতের সাথে বাংলাদেশের সীমান্ত দৈর্ঘ্য কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৩৭১৫ কিলোমিটার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৩-> দেশের প্রথম কৃত্রিম উপগ্রহ বঙ্গবন্ধু-১ কবে উৎক্ষেপণ করা হয়?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১১ মে ২০১৮",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৪-> বাংলাদেশ-মিয়ানমার মৈত্রী সেতু কোথায় অবস্থিত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  কক্সবাজার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৫-> কবে বিশ্বব্যাংক বাংলাদেশকে নিম্ন মধ্যম আয়ের দেশের তালিকায় অন্তর্ভুক্ত করে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১ জুলাই ২০১৫",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৬-> বাংলাদেশের সাথে ভারতের সীমানা কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৪১৫৬ কি.মি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৭-> বাংলাদেশের ক্ষেত্রফল কত বর্গমাইল ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৫৬,৫০১ বর্গমাইল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৮-> শেওলা স্থলবন্দর কোথায় অবস্থিত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  সিলেট",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ২৯-> সিলেট জেলার উত্তরে কোন ভারতীয় রাজ্য অবস্থিত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  মেঘালয়",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩০-> বাংলাদেশর মোট সীমারেখার পরিমাপ কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৫১৩৮ কি.মি.",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩১-> টাঙ্গুয়ার হাওড়ের আয়তন কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১০০ বর্গ কিমি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩২-> জাফলং ভূতাত্ত্বিক ঐতিহ্য-এর আয়তন কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২২.৫৯ একর",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৩-> 'শুভলং' ঝরণা কোন জেলায় অবস্থিত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  রাঙামাটি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৪-> বাংলাদেশের সীমান্তবর্তী কোন জেলার সাথে ভারতের কোন সংযোগ নেই?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  বান্দরবান",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৫-> বাংলাদেশের আয়াতন কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১,৪৭,৫৭০ বর্গ কিলোমিটার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৬-> জাতীয় পতাকার মাঝে লাল বিত্ত কিসের প্রতীক?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  স্বাধীনতার নতুন সূর্যের",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৭-> 'আমার সোনার বাংলা' কবিতায় কতটি চরণ আছে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২৫ টি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৮-> 'আমার সোনার বাংলা' কবিতায় কতটি চরণ আছে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২৫ টি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৮-> বাংলাদেশ স্বাধীনতা লাভ করেছে কবে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১৯৭১ সালের ১৬ই ডিসেম্বর",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৮-> বাংলাদেশ স্বাধীনতা লাভ করেছে কবে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১৯৭১ সালের ১৬ই ডিসেম্বর",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৩৯-> বাংলাদেশের বাণিজ্যিক রাজধানীর নাম কি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  চট্রগ্রাম",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪০-> আয়াতনের ভিত্তিতে পৃথিবীতে বাংলাদেশের অবস্থান কত তম?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৯০ তম",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪১-> বাংলাদেশের রাজনৈতিক সমুদ্রসীমা কত নটিক্যাল মাইল?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১২",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪২-> ভারতের সাথে বাংলাদেশের সীমান্তবর্তী জেলা কয়টি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৩০",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৩-> মিয়ানমারের সাথে বাংলাদেশের সীমান্তের দৈর্ঘ্য কত কিলোমিটার?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২৮০ কিলোমিটার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৪-> পঞ্চম আদমশুমারি তথ্য অনুযায়ী জনসংখ্যায় ক্ষুদ্রতম জেলা কোনটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  বান্দরবান",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৫-> মেয়র মোহাম্মদ হানিফ ফ্লাইওভারের দৈর্ঘ্য কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১১.৮ কিমি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৬-> বাংলাদেশর মোট সীমানার দৈর্ঘ্য (জল ও স্থলসহ) কত ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২৯২৮ মাইল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৭-> বাংলাদেশের প্রথম কম্পিউটার প্রোগ্রামার কে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  হাফিজউদ্দিন মিয়া",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৮-> বাংলাদেশের কোন জেলাটির সাথে ভারত ও মিয়ানমারের সীমানা রয়েছে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  রাঙ্গামাটি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৪৯-> বৈদেশিক মুদ্রার রিজার্ভের অর্থ দিয়ে সরকার কি নামে তহবিল গঠন করবে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  বাংলাদেশ সার্বভৌম সম্পদ তহবিল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫০-> দেশের ২২তম স্থলবন্দর কোনটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  শেওলা",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫১-> বাংলাদেশের মোট সীমানার দৈর্ঘ্য (জল ও স্থলসহ) কত ?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২৯২৮ মাইল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫২-> উপকূল হতে বাংলাদেশের অর্থনৈতিক সমুদ্রসীমা কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ২০০ নটিক্যাল মাইল",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৩-> বাংলাদেশের সমুদ্র উপকূলের দৈর্ঘ্য কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৭১১ কি.মি.",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৪-> যে দুটি দেশের সাথে বাংলাদেশের সীমানা রয়েছে সে দুটির নাম কি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ভারত ও মায়ানমার",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৫-> বাংলাদেশের রণসঙ্গীতের রচয়িতা কে?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  কাজী নজরুল ইসলাম",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৬-> বাংলাদেশের ক্ষুদ্রতম ইউনিয়ন পরিষদ কোনটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  সেন্টমার্টিন",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৭-> জাতীয় স্মৃতিসৌধের উচ্চতা কত?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ১৫০ ফুট",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৮-> জাতীয় পতাকার সবুজ বর্ণ কিসের প্রতীক?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  তারুণ্যের উদ্দীপনা",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৫৯-> বাংলাদেশে আবহাওয়া অফিস কয়টি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ৩৫ টি",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
            SizedBox(height: 10,),
            ListTile(
              tileColor: Colors.white,
              minVerticalPadding: 20,
              title: Text("প্রশ্ন ৬০-> বাংলাদেশের বৃহত্তম দ্বীপ কোনটি?",
                style: TextStyle(fontSize: 20,fontWeight: FontWeight.bold,fontFamily: 'BalooDa2-Medium'),),
              subtitle: Text("উত্তরঃ  ভোলা",
                style: TextStyle(fontSize: 19,fontWeight: FontWeight.bold,
                  fontFamily: 'BalooDa2-Medium',color: Colors.blue,),),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
            ),
          ],
        ),
      ),

    );
  }
}
